# Generated by Django 3.0.7 on 2020-06-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kda', models.CharField(max_length=30)),
                ('player1', models.CharField(max_length=30)),
                ('player2', models.CharField(max_length=30)),
                ('p1_damage', models.IntegerField()),
                ('p2_damage', models.IntegerField()),
                ('p1_wins', models.IntegerField()),
                ('p2_wins', models.IntegerField()),
                ('champion_name_p1', models.CharField(max_length=30)),
                ('champion_name_p2', models.CharField(max_length=30)),
            ],
        ),
    ]
