# Generated by Django 3.0.7 on 2020-06-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='kda',
        ),
        migrations.AddField(
            model_name='games',
            name='game_type',
            field=models.CharField(choices=[('ranked_sd', 'Ranked solo duo'), ('flex', 'Ranked flex'), ('normal', 'Normal'), ('draft', 'Draft'), ('aram', 'Aram')], default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='games',
            name='kda_p1',
            field=models.CharField(default='0/0/0', max_length=30),
        ),
        migrations.AddField(
            model_name='games',
            name='kda_p2',
            field=models.CharField(default='0/0/0', max_length=30),
        ),
    ]
