# Generated by Django 3.0.7 on 2020-06-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200630_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
