# Generated by Django 3.1.2 on 2020-12-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('riot_game_id', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('platform_id', models.CharField(default=None, max_length=10)),
                ('queue', models.IntegerField(default=0)),
                ('season', models.IntegerField(default=0)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('game_duration', models.IntegerField(default=0)),
                ('_map', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Summoners',
            fields=[
                ('_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('accountId', models.CharField(default=None, max_length=100)),
                ('puuid', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(default=None, max_length=30)),
                ('profileIconId', models.IntegerField(default=None)),
                ('summonerLevel', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summonerName', models.CharField(default=None, max_length=30)),
                ('accountId', models.CharField(default=None, max_length=100)),
                ('profileIcon', models.IntegerField(default=None)),
                ('participantId', models.IntegerField(default=None)),
                ('teamId', models.IntegerField(default=None)),
                ('championId', models.IntegerField(default=None)),
                ('spell1Id', models.IntegerField(default=None)),
                ('spell2Id', models.IntegerField(default=None)),
                ('win', models.IntegerField(default=None)),
                ('item0', models.IntegerField(default=None)),
                ('item1', models.IntegerField(default=None)),
                ('item2', models.IntegerField(default=None)),
                ('item3', models.IntegerField(default=None)),
                ('item4', models.IntegerField(default=None)),
                ('item5', models.IntegerField(default=None)),
                ('item6', models.IntegerField(default=None)),
                ('kills', models.IntegerField(default=None)),
                ('deaths', models.IntegerField(default=None)),
                ('assists', models.IntegerField(default=None)),
                ('totalDamageDealtToChampions', models.IntegerField(default=None)),
                ('damageDealtToTurrets', models.IntegerField(default=None)),
                ('visionScore', models.IntegerField(default=None)),
                ('totalDamageTaken', models.IntegerField(default=None)),
                ('visionWardsBoughtInGame', models.IntegerField(default=None)),
                ('_game', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='league.games')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='gamer',
            field=models.ManyToManyField(to='league.Summoners'),
        ),
    ]
