# Generated by Django 3.0.7 on 2020-07-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kda_p1', models.CharField(default='0/0/0', max_length=30)),
                ('kda_p2', models.CharField(default='0/0/0', max_length=30)),
                ('player1', models.CharField(max_length=30)),
                ('player2', models.CharField(max_length=30)),
                ('p1_damage', models.IntegerField()),
                ('p2_damage', models.IntegerField()),
                ('p1_wins', models.IntegerField()),
                ('p2_wins', models.IntegerField()),
                ('champion_name_p1', models.CharField(max_length=30)),
                ('champion_name_p2', models.CharField(max_length=30)),
                ('game_type', models.CharField(choices=[('ranked_sd', 'Ranked solo duo'), ('flex', 'Ranked flex'), ('normal', 'Normal'), ('draft', 'Draft'), ('aram', 'Aram')], default='Unknown', max_length=10)),
                ('game_id', models.CharField(default='None', max_length=50)),
            ],
        ),
    ]
