# Generated by Django 3.0.7 on 2020-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200709_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Ranked solo duo', 'ranked_sd'), ('Ranked flex', 'flex'), ('Normal', 'normal'), ('Draft', 'draft'), ('Aram', 'aram')], default='Unknown', max_length=30),
        ),
    ]
